locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://komyeonghoon.github.io/baseball_website/"
baseurl                  : # the subpath of your site, e.g. "/blog"
