locale                   : "en-US"
title                    : "baseball world!!"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Your Name"
description              : "An amazing website."
url                      : ""
baseurl                  : ""
