locale                   : "en-US"
title                    : "ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://komyeonghoon.github.io/"
baseurl                  : ""
