locale                   : "en-US"
title                    : ""
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://komyeonghoon.github.io/baseball_website/"
baseurl                  : ""
